### ISSUE TITLE
[Enhancement] Bump Ansible Playbook to run OpenSearch/Dashboards 1.1.0.

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/ansible-playbook#11]
**Is your feature request related to a problem? Please describe.**
[Enhancement] Bump Ansible Playbook to run OpenSearch/Dashboards 1.1.0.

1.2.0 is coming and 1.1.0 already released.
We should start setting the default version to 1.1.0 for playbooks.
Also suggest having long live branches such as 1.x, 2.x so main will be the unstable branch.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**

**Additional context**

**Comment by peterzhuamazon** [comment]
@saravanan30erd please take a look on this and let me know your thoughts.
Thanks.

**Comment by saravanan30erd** [comment]
@peterzhuamazon sure, I can update version 1.1.0 and will raise PR.

But I don't think creating  long live branches such as 1.x, 2.x for managing the versions because it will become very difficult to manage many branches in future.

I think we should use github `Releases & Tags` feature to manage multiple versions. 
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

We can use the same release version of the product, use main branch as unstable branch with all new changes.
Example: current playbook deploys opensearch & dashboard 1.0.1 version so we can create a release with version 1.0.1. 
 Same for next versions.

Let me know your feedback.

**Comment by peterzhuamazon** [comment]
Is there a playbook version vs app(opensearch) version in Ansible Playbook?
If you check our helm charts repo it is releasing a new charts version every PR, but the App Version stays with the OpenSearch version.

Also, we just release documentations for Ansible: https://opensearch.org/docs/latest/opensearch/install/ansible/
Let me know if you think we need to improve this.
If so, you can send PRs to https://github.com/opensearch-project/documentation-website.

Thanks.

**Comment by saravanan30erd** [comment]
`Is there a playbook version vs app(opensearch) version in Ansible Playbook?`
No. Unlike Helm charts, Ansible playbooks doesn't have versioning feature as in-built so we need to manage the playbook version outside. so I think its better to match the opensearch version for playbook releases.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon `Is there a playbook version vs app(opensearch) version in Ansible Playbook?` No. Unlike Helm charts, Ansible playbooks doesn't have versioning feature as in-built so we need to manage the playbook version outside. so I think its better to match the opensearch version for playbook releases.

I can release 1.0.1 before merging this PR tho, do you find the current state stable for cutting a tag?

Thanks.

**Comment by saravanan30erd** [comment]
@peterzhuamazon  Yes, current main branch is working fine for version 1.0.1. 
After merging this PR, you can create release for 1.1.0. I am planning to add multi-node installation soon which I will start in 1.1.0.

**Comment by peterzhuamazon** [comment]
Thanks. Release 1.0.1 now and will ask others to approve 1.1.0 as well.
To make things easy I think we will keep this main branch rolling with 1.1.0 until 1.2.0 release, then we cut tag for 1.1.0.
Thoughts?

**Comment by saravanan30erd** [comment]
>  To make things easy I think we will keep this main branch rolling with 1.1.0 until 1.2.0 release, then we cut tag for 1.1.0. Thoughts?
Sure
