### ISSUE TITLE
 [Enhancement] Bump Ansible Playbook to run OpenSearch/Dashboards 1.2.0.

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/ansible-playbook#15]
**Is your feature request related to a problem? Please describe.**
[Enhancement] Bump Ansible Playbook to run OpenSearch/Dashboards 1.2.0.

1.3.0 is coming and 1.2.0 already released.
We should start setting the default version to 1.2.0 for playbooks.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**

**Additional context**

**Comment by saravanan30erd** [comment]
@peterzhuamazon  Sure, I will update and test it with 1.2.0. 
I think you can create new tag 1.1.0 now with current state.

**Comment by peterzhuamazon** [comment]
Tags created, merged 1.2.0 as well now. Thanks.
