### ISSUE TITLE
[Enhancement]Need to separate OpenSearch vs Dashboards version in Ansible Playbook

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/ansible-playbook#18]
**Is your feature request related to a problem? Please describe.**
It is possible that a OpenSearch and Dashboards binaries having different version.
Ex: 1.1.1 Dashboards can still use for OpenSearch 1.1.0.

As of now it seems their versions are controlled by a single version number.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saravanan30erd** [comment]
@peterzhuamazon  raised PR for this.
