### ISSUE TITLE
[BUG][Security Plugin Configuration]

### ISSUE THREAD

**Issue by rodolfovillordo** [opensearch-project/ansible-playbook#80]
**Describe the bug**

The Playbook execution fails at the task `Security Plugin configuration | Copy the opensearch security internal users template execution` on a single-node deployment. Tested on an EC2 Ubuntu instance.

**To Reproduce**
1. checkout the latest version from this repository
2. ~~[Change the cluster_type ](https://github.com/opensearch-project/ansible-playbook#single-node-installation)variable to single-node~~ unnecessary step ref: https://github.com/opensearch-project/ansible-playbook/pull/81#issuecomment-1190240510
3. configure the inventory hosts as below

```
aos ansible_host=<public_ip> ansible_user=ubuntu ip=<private_ip> roles=data,master

dashboards1 ansible_host=<2nd_instance_public_ip> ansible_user=ubuntu ip=<second_instance_private_ip>

# List all the nodes in the os cluster
[os-cluster]
aos

# List all the Master eligible nodes under this group
[master]
aos

[dashboards]
dashboards1
```
```
TASK [linux/opensearch : Security Plugin configuration | Copy the opensearch security internal users template] *******************************************************************************
fatal: [aos]: FAILED! => {"changed": false, "checksum": "17c615cd8e9089aedb31891e7aedd1ff8fa32318", "msg": "Destination directory /usr/share/opensearch/plugins/opensearch-security/securityconfig does not exist"}
```

**Expected behavior**
Finish the deployment without errors.

**Playbook Name**
Specify the Playbook which is affected?
roles/linux/opensearch/tasks/security.yml

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - Ansible Version: 2.12.6
 - Playbook Version: 2.1.0

**Additional context**
The task `Security Plugin configuration | Copy the opensearch security internal users template execution` assumes that the `{{ os_sec_plugin_conf_path }}` already exists when copying the internal_users template. However, the template module does not create parent directories.

**Comment by rodolfovillordo** [comment]
PR for the fix: https://github.com/opensearch-project/ansible-playbook/pull/81

**Comment by minhthong582000** [comment]
Hi, @rodolfovillordo. Starting from version 2.x.x, the opensearch-security configuration files are moved to `/usr/share/opensearch/config/opensearch-security`. So if we specify the `os_sec_plugin_conf_path` like this, everything works fine:

```yaml
os_sec_plugin_conf_path: /usr/share/opensearch/config/opensearch-security
```

Already tested on my local machines.

Related MR: https://github.com/opensearch-project/security/pull/1749

**Comment by peterzhuamazon** [comment]
> @rodolfovillordo. Starting from version 2.x.x, the opensearch-security configuration files are moved to `/usr/share/opensearch/config/opensearch-security`. So if we specify the `os_sec_plugin_conf_path` like this, everything works fine:
> 
> ```yaml
> os_sec_plugin_conf_path: /usr/share/opensearch/config/opensearch-security
> ```
> 
> Already tested on my local machines.
> 
> Related MR: [opensearch-project/security#1749](https://github.com/opensearch-project/security/pull/1749)

The path in 2.x is moved to `opensearchroot/config/opensearch-security` not in `plugins/opensearch-security/securityconfig` anymore.
